module.exports = {
  content: [
    './app/**/*.php',
    './public/**/*.php',
  ],
  safelist: [
    "flex",
    "inline-flex",
    "block",
    "inline-block",
    "hidden",
    "items-center",
    "items-start",
    "items-end",
    "justify-between",
    "justify-center",
    "justify-end",
    "justify-start",
    "flex-1",
    "flex-shrink-0",
    "gap-1",
    "gap-2",
    "gap-4",
    "gap-6",
    "h-16",
    "w-full",
    "max-w-screen-xl",
    "px-4",
    "sm:px-6",
    "lg:px-8",
    "rounded",
    "rounded-full",
    "rounded-md",
    "border",
    "shadow",
    "shadow-inner",
    "transition",
    "text-sm",
    "text-lg",
    "text-xl",
    "text-center",
    "ml-auto",
    // Responsive variants
    "md:flex",
    "md:block",
    "md:hidden",
    "md:items-center",
    "md:gap-12",
    "md:relative",
    "md:justify-center",
    "md:w-auto",
    "md:px-0",
    "md:py-0",
    "md:mt-0",
    "md:mb-0",
    "md:ml-0",
    "md:mr-0",
    "md:rounded",
    "md:rounded-md",
    "md:rounded-full",
    "md:shadow",
    "md:shadow-inner",
    "md:transition",
    // Spacing utilities (margin, padding)
    ...Array.from({length: 97}, (_, i) => `m-${i}`),
    ...Array.from({length: 97}, (_, i) => `mx-${i}`),
    ...Array.from({length: 97}, (_, i) => `my-${i}`),
    ...Array.from({length: 97}, (_, i) => `mt-${i}`),
    ...Array.from({length: 97}, (_, i) => `mb-${i}`),
    ...Array.from({length: 97}, (_, i) => `ml-${i}`),
    ...Array.from({length: 97}, (_, i) => `mr-${i}`),
    ...Array.from({length: 97}, (_, i) => `p-${i}`),
    ...Array.from({length: 97}, (_, i) => `px-${i}`),
    ...Array.from({length: 97}, (_, i) => `py-${i}`),
    ...Array.from({length: 97}, (_, i) => `pt-${i}`),
    ...Array.from({length: 97}, (_, i) => `pb-${i}`),
    ...Array.from({length: 97}, (_, i) => `pl-${i}`),
    ...Array.from({length: 97}, (_, i) => `pr-${i}`),
    // Sizing utilities (width, height)
    ...Array.from({length: 97}, (_, i) => `w-${i}`),
    ...Array.from({length: 97}, (_, i) => `h-${i}`),
    // Add more as needed for your project!
  ],
  theme: {
    extend: {
      colors: {
        text: 'var(--text)',
        background: 'var(--background)',
        primary: 'var(--primary)',
        secondary: 'var(--secondary)',
        accent: 'var(--accent)',
      },
    },
  },
  plugins: [],
}
